{{- if eq .Release.Namespace "kube-system" }}
apiVersion: {{ include "apiVersion" . }}
kind: RoleBinding
metadata:
  name: system:deployers
roleRef:
  name: system:deployer
subjects:
- kind: ServiceAccount
  name: deployer
groupNames: null
userNames:
- system:serviceaccount:{{ .Release.Namespace }}:deployer
{{- end }}
